-- Auto-generated quotes from CSV
-- Total quotes: 3000

-- Inserting 410 quotes

INSERT INTO public.quotes (content, author, category) VALUES
  ('“Be yourself; everyone else is already taken.”', 'Oscar Wilde', 'Motivation'),
  ('“You''ve gotta dance like there''s nobody watching,Love like you''ll never be hurt,Sing like there''s nobody listening,And live like it''s heaven on earth.”', 'William W. Purkey', 'Motivation'),
  ('“Be the change that you wish to see in the world.”', 'Mahatma Gandhi', 'Motivation'),
  ('“Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.”', 'Martin Luther King Jr.', 'Motivation'),
  ('“We accept the love we think we deserve.”', 'Stephen Chbosky', 'Motivation'),
  ('“Without music, life would be a mistake.”', 'Friedrich Nietzsche', 'Motivation'),
  ('“Twenty years from now you will be more disappointed by the things that you didn''t do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.”', 'H. Jackson Brown Jr.', 'Motivation'),
  ('“All that is gold does not glitter,Not all those who wander are lost;The old that is strong does not wither,Deep roots are not reached by the frost.From the ashes a fire shall be woken,A light from the shadows shall spring;Renewed shall be blade that was broken,The crownless again shall be king.”', 'J.R.R. Tolkien', 'Motivation'),
  ('“Imperfection is beauty, madness is genius and it''s better to be absolutely ridiculous than absolutely boring.”', 'Marilyn Monroe', 'Motivation'),
  ('“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”', 'Albert Einstein', 'Motivation'),
  ('“We are all in the gutter, but some of us are looking at the stars.”', 'Oscar Wilde', 'Motivation'),
  ('“Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.”', 'Neil Gaiman', 'Motivation'),
  ('“Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.”', 'Bill Keane', 'Motivation'),
  ('“I have not failed. I''ve just found 10,000 ways that won''t work.”', 'Thomas A. Edison', 'Motivation'),
  ('“The opposite of love is not hate, it''s indifference. The opposite of art is not ugliness, it''s indifference. The opposite of faith is not heresy, it''s indifference. And the opposite of life is not death, it''s indifference.”', 'Elie Wiesel', 'Motivation'),
  ('“I am enough of an artist to draw freely upon my imagination. Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.”', 'Albert Einstein', 'Motivation'),
  ('“Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.”', 'Lao Tzu', 'Motivation'),
  ('“You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. You''re on your own. And you know what you know. And YOU are the one who''ll decide where to go...”', 'Dr. Seuss', 'Motivation'),
  ('“That which does not kill us makes us stronger.”', 'Friedrich Nietzsche', 'Motivation'),
  ('“It is never too late to be what you might have been.”', 'George Eliot', 'Motivation'),
  ('“It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.”', 'J.K. Rowling', 'Motivation'),
  ('“There is no greater agony than bearing an untold story inside you.”', 'Maya Angelou', 'Motivation'),
  ('“Everything you can imagine is real.”', 'Pablo Picasso', 'Motivation'),
  ('“You can never get a cup of tea large enough or a book long enough to suit me.”', 'C.S. Lewis', 'Motivation'),
  ('“Life isn''t about finding yourself. Life is about creating yourself.”', 'George Bernard Shaw', 'Motivation'),
  ('“To the well-organized mind, death is but the next great adventure.”', 'J.K. Rowling', 'Motivation'),
  ('“You don''t get to choose if you get hurt in this world...but you do have some say in who hurts you. I like my choices.”', 'John Green', 'Motivation'),
  ('“Do what you can, with what you have, where you are.”', 'Theodore Roosevelt', 'Motivation'),
  ('“Success is not final, failure is not fatal: it is the courage to continue that counts.”', 'Winston S. Churchill', 'Motivation'),
  ('“When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.”', 'Helen Keller', 'Motivation'),
  ('“So, this is my life. And I want you to know that I am both happy and sad and I''m still trying to figure out how that could be.”', 'Stephen Chbosky', 'Motivation'),
  ('“Listen to the mustn''ts, child. Listen to the don''ts. Listen to the shouldn''ts, the impossibles, the won''ts. Listen to the never haves, then listen close to me... Anything can happen, child. Anything can be.”', 'Shel Silverstein', 'Motivation'),
  ('“Things change. And friends leave. Life doesn''t stop for anybody.”', 'Stephen Chbosky', 'Motivation'),
  ('“And, when you want something, all the universe conspires in helping you to achieve it.”', 'Paulo Coelho', 'Motivation'),
  ('“You may say I''m a dreamer, but I''m not the only one. I hope someday you''ll join us. And the world will live as one.”', 'John Lennon', 'Motivation'),
  ('“He has achieved success who has lived well, laughed often, and loved much;Who has enjoyed the trust of pure women, the respect of intelligent men and the love of little children;Who has filled his niche and accomplished his task;Who has never lacked appreciation of Earth''s beauty or failed to express it;Who has left the world better than he found it,Whether an improved poppy, a perfect poem, or a rescued soul;Who has always looked for the best in others and given them the best he had;Whose life was an inspiration;Whose memory a benediction.”', 'Bessie Anderson Stanley', 'Motivation'),
  ('“We are what we pretend to be, so we must be careful about what we pretend to be.”', 'Kurt Vonnegut', 'Motivation'),
  ('“Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness that most frightens us. We ask ourselves, ''Who am I to be brilliant, gorgeous, talented, fabulous?'' Actually, who are you not to be? You are a child of God. Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won''t feel insecure around you. We are all meant to shine, as children do. We were born to make manifest the glory of God that is within us. It''s not just in some of us; it''s in everyone. And as we let our own light shine, we unconsciously give other people permission to do the same. As we are liberated from our own fear, our presence automatically liberates others.”', 'Marianne Williamson', 'Motivation'),
  ('“It takes courage to grow up and become who you really are.”', 'E.E. Cummings', 'Motivation'),
  ('“We believe in ordinary acts of bravery, in the courage that drives one person to stand up for another.”', 'Veronica Roth', 'Motivation'),
  ('“It''s the possibility of having a dream come true that makes life interesting.”', 'Paulo Coelho', 'Motivation'),
  ('“What you''re supposed to do when you don''t like a thing is change it. If you can''t change it, change the way you think about it. Don''t complain.”', 'Maya Angelou', 'Motivation'),
  ('“He’s not perfect. You aren’t either, and the two of you will never be perfect. But if he can make you laugh at least once, causes you to think twice, and if he admits to being human and making mistakes, hold onto him and give him the most you can. He isn’t going to quote poetry, he’s not thinking about you every moment, but he will give you a part of him that he knows you could break. Don’t hurt him, don’t change him, and don’t expect for more than he can give. Don’t analyze. Smile when he makes you happy, yell when he makes you mad, and miss him when he’s not there. Love hard when there is love to be had. Because perfect guys don’t exist, but there’s always one guy that is perfect for you.”', 'Bob Marley', 'Motivation'),
  ('“A person''s a person, no matter how small.”', 'Dr. Seuss', 'Motivation'),
  ('“I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration. I will face my fear. I will permit it to pass over me and through me. And when it has gone past I will turn the inner eye to see its path. Where the fear has gone there will be nothing. Only I will remain.”', 'Frank Herbert', 'Motivation'),
  ('“When we honestly ask ourselves which person in our lives mean the most to us, we often find that it is those who, instead of giving advice, solutions, or cures, have chosen rather to share our pain and touch our wounds with a warm and tender hand. The friend who can be silent with us in a moment of despair or confusion, who can stay with us in an hour of grief and bereavement, who can tolerate not knowing, not curing, not healing and face with us the reality of our powerlessness, that is a friend who cares.”', 'Henri Nouwen', 'Motivation'),
  ('“You can''t live your life for other people. You''ve got to do what''s right for you, even if it hurts some people you love.”', 'Nicholas Sparks', 'Motivation'),
  ('“I am no bird; and no net ensnares me: I am a free human being with an independent will.”', 'Charlotte Brontë', 'Motivation'),
  ('“Well-behaved women seldom make history.”', 'Laurel Thatcher Ulrich', 'Motivation'),
  ('“So we beat on, boats against the current, borne back ceaselessly into the past.”', 'F. Scott Fitzgerald', 'Motivation'),
  ('“Everyone thinks of changing the world, but no one thinks of changing himself.”', 'Leo Tolstoy', 'Motivation'),
  ('“When I despair, I remember that all through history the way of truth and love have always won. There have been tyrants and murderers, and for a time, they can seem invincible, but in the end, they always fall. Think of it--always.”', 'Mahatma Gandhi', 'Motivation'),
  ('“Nothing is impossible, the word itself says ''I''m possible''!”', 'Audrey Hepburn', 'Motivation'),
  ('“[...]the only people for me are the mad ones, the ones who are mad to live, mad to talk, mad to be saved, desirous of everything at the same time, the ones who never yawn or say a commonplace thing, but burn, burn, burn like fabulous yellow roman candles exploding like spiders across the stars and in the middle you see the blue centerlight pop and everybody goes “Awww!”', 'Jack Kerouac', 'Motivation'),
  ('“Do what you feel in your heart to be right – for you’ll be criticized anyway.”', 'Eleanor Roosevelt', 'Motivation'),
  ('“I can''t give you a sure-fire formula for success, but I can give you a formula for failure: try to please everybody all the time.”', 'Herbert Bayard Swope', 'Motivation'),
  ('“Never doubt that a small group of thoughtful, committed, citizens can change the world. Indeed, it is the only thing that ever has.”', 'Margaret Mead', 'Motivation'),
  ('“Happiness is not something ready made. It comes from your own actions.”', 'Dalai Lama XIV', 'Motivation'),
  ('“All we have to decide is what to do with the time that is given us.”', 'J.R.R. Tolkien', 'Motivation'),
  ('“We are only as strong as we are united, as weak as we are divided.”', 'J.K. Rowling', 'Motivation'),
  ('“The weak can never forgive. Forgiveness is the attribute of the strong.”', 'Mahatma Gandhi', 'Motivation'),
  ('“Do not read, as children do, to amuse yourself, or like the ambitious, for the purpose of instruction. No, read in order to live.”', 'Gustave Flaubert', 'Motivation'),
  ('“Peace begins with a smile..”', 'Mother Teresa', 'Motivation'),
  ('“In the depth of winter, I finally learned that within me there lay an invincible summer.”', 'Albert Camus', 'Motivation'),
  ('“Imagining the future is a kind of nostalgia. (...) You spend your whole life stuck in the labyrinth, thinking about how you''ll escape it one day, and how awesome it will be, and imagining that future keeps you going, but you never do it. You just use the future to escape the present.”', 'John Green', 'Motivation'),
  ('“Friendship is unnecessary, like philosophy, like art.... It has no survival value; rather it is one of those things which give value to survival.”', 'C.S. Lewis', 'Motivation'),
  ('“I hope she''ll be a fool -- that''s the best thing a girl can be in this world, a beautiful little fool.”', 'F. Scott Fitzgerald', 'Motivation'),
  ('“For attractive lips, speak words of kindness.For lovely eyes, seek out the good in people.For a slim figure, share your food with the hungry.For beautiful hair, let a child run his fingers through it once a day.For poise, walk with the knowledge you’ll never walk alone....We leave you a tradition with a future.The tender loving care of human beings will never become obsolete.People even more than things have to be restored, renewed, revived, reclaimed and redeemed and redeemed and redeemed.Never throw out anybody.Remember, if you ever need a helping hand, you’ll find one at the end of your arm.As you grow older, you will discover that you have two hands: one for helping yourself, the other for helping others.Your “good old days” are still ahead of you, may you have many of them.”', 'Sam Levenson', 'Motivation'),
  ('“Don''t think or judge, just listen.”', 'Sarah Dessen', 'Motivation'),
  ('“Promise YourselfTo be so strong that nothingcan disturb your peace of mind.To talk health, happiness, and prosperityto every person you meet.To make all your friends feelthat there is something in themTo look at the sunny side of everythingand make your optimism come true.To think only the best, to work only for the best,and to expect only the best.To be just as enthusiastic about the success of othersas you are about your own.To forget the mistakes of the pastand press on to the greater achievements of the future.To wear a cheerful countenance at all timesand give every living creature you meet a smile.To give so much time to the improvement of yourselfthat you have no time to criticize others.To be too large for worry, too noble for anger, too strong for fear,and too happy to permit the presence of trouble.To think well of yourself and to proclaim this fact to the world,not in loud words but great deeds.To live in faith that the whole world is on your sideso long as you are true to the best that is in you.”', 'Christian D. Larson', 'Motivation'),
  ('“Grief does not change you, Hazel. It reveals you.”', 'John Green', 'Motivation'),
  ('“Who controls the past controls the future. Who controls the present controls the past.”', 'George Orwell', 'Motivation'),
  ('“Whatever you are, be a good one.”', 'Abraham Lincoln', 'Motivation'),
  ('“And once the storm is over, you won’t remember how you made it through, how you managed to survive. You won’t even be sure, whether the storm is really over. But one thing is certain. When you come out of the storm, you won’t be the same person who walked in. That’s what this storm’s all about.”', 'Haruki Murakami', 'Motivation'),
  ('“Two wrongs don''t make a right, but they make a good excuse.”', 'Thomas Szasz', 'Motivation'),
  ('“Attitude is a choice. Happiness is a choice. Optimism is a choice. Kindness is a choice. Giving is a choice. Respect is a choice. Whatever choice you make makes you. Choose wisely.”', 'Roy T. Bennett', 'Motivation'),
  ('“If my life is going to mean anything, I have to live it myself.”', 'Rick Riordan', 'Motivation'),
  ('“First they ignore you. Then they ridicule you. And then they attack you and want to burn you. And then they build monuments to you.”', 'Nicholas Klein', 'Motivation'),
  ('“Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.”', 'Rumi', 'Motivation'),
  ('“Don''t be pushed around by the fears in your mind. Be led by the dreams in your heart.”', 'Roy T. Bennett', 'Motivation'),
  ('“I believe that imagination is stronger than knowledge. That myth is more potent than history. That dreams are more powerful than facts. That hope always triumphs over experience. That laughter is the only cure for grief. And I believe that love is stronger than death.”', 'Robert Fulghum', 'Motivation'),
  ('“The fault, dear Brutus, is not in our stars, but in ourselves.”', 'William Shakespeare', 'Motivation'),
  ('“Isn''t it nice to think that tomorrow is a new day with no mistakes in it yet?”', 'L.M. Montgomery', 'Motivation'),
  ('“You can''t stay in your corner of the Forest waiting for others to come to you. You have to go to them sometimes.”', 'A.A. Milne', 'Motivation'),
  ('“Hope is the thing with feathers That perches in the soul And sings the tune without the words And never stops at all.”', 'Emily Dickinson', 'Motivation'),
  ('“Pain is inevitable. Suffering is optional.”', 'haruki murakami', 'Motivation'),
  ('“Instead of worrying about what you cannot control, shift your energy to what you can create.”', 'Roy T. Bennett', 'Motivation'),
  ('“I have no special talents. I am only passionately curious.”', 'Albert Einstein', 'Motivation'),
  ('“The mind is its own place, and in itself can make a heaven of hell, a hell of heaven..”', 'John Milton', 'Motivation'),
  ('“I wanted you to see what real courage is, instead of getting the idea that courage is a man with a gun in his hand. It''s when you know you''re licked before you begin, but you begin anyway and see it through no matter what.”', 'Harper Lee', 'Motivation'),
  ('“When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down ‘happy’. They told me I didn’t understand the assignment, and I told them they didn’t understand life.”', 'John Lennon', 'Motivation'),
  ('“Always do what you are afraid to do.”', 'Ralph Waldo Emerson', 'Motivation'),
  ('“There is neither happiness nor misery in the world; there is only the comparison of one state with another, nothing more. He who has felt the deepest grief is best able to experience supreme happiness. We must have felt what it is to die, Morrel, that we may appreciate the enjoyments of life. " Live, then, and be happy, beloved children of my heart, and never forget, that until the day God will deign to reveal the future to man, all human wisdom is contained in these two words, ''Wait and Hope.”', 'Alexandre Dumas', 'Motivation'),
  ('“Hell is empty and all the devils are here.”', 'William Shakespeare', 'Motivation'),
  ('“Talent hits a target no one else can hit. Genius hits a target no one else can see.”', 'Arthur Schopenhauer', 'Motivation'),
  ('“That''s always seemed so ridiculous to me, that people want to be around someone because they''re pretty. It''s like picking your breakfeast cereals based on color instead of taste.”', 'John Green', 'Motivation'),
  ('“Our lives begin to end the day we become silent about things that matter.”', 'Martin Luther King Jr.', 'Motivation'),
  ('“The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair, and though in all lands love is now mingled with grief, it grows perhaps the greater.”', 'J.R.R. Tolkien', 'Motivation'),
  ('“In the end, we will remember not the words of our enemies, but the silence of our friends.”', 'Martin Luther King Jr.', 'Motivation'),
  ('“Do not let your fire go out, spark by irreplaceable spark in the hopeless swamps of the not-quite, the not-yet, and the not-at-all. Do not let the hero in your soul perish in lonely frustration for the life you deserved and have never been able to reach. The world you desire can be won. It exists.. it is real.. it is possible.. it''s yours.”', 'Ayn Rand', 'Motivation'),
  ('“I''m selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can''t handle me at my worst, then you sure as hell don''t deserve me at my best.”', 'Marilyn Monroe', 'Wisdom'),
  ('“Two things are infinite: the universe and human stupidity; and I''m not sure about the universe.”', 'Albert Einstein', 'Wisdom'),
  ('“A room without books is like a body without a soul.”', 'Marcus Tullius Cicero', 'Wisdom'),
  ('“Be who you are and say what you feel, because those who mind don''t matter, and those who matter don''t mind.”', 'Bernard M. Baruch', 'Wisdom'),
  ('“You only live once, but if you do it right, once is enough.”', 'Mae West', 'Wisdom'),
  ('“In three words I can sum up everything I''ve learned about life: it goes on.”', 'Robert Frost', 'Wisdom'),
  ('“If you want to know what a man''s like, take a good look at how he treats his inferiors, not his equals.”', 'J.K. Rowling', 'Wisdom'),
  ('“Don’t walk in front of me… I may not followDon’t walk behind me… I may not leadWalk beside me… just be my friend”', 'Albert Camus', 'Wisdom'),
  ('“If you tell the truth, you don''t have to remember anything.”', 'Mark Twain', 'Wisdom'),
  ('“Friendship ... is born at the moment when one man says to another "What! You too? I thought that no one but myself . . .”', 'C.S. Lewis', 'Wisdom'),
  ('“I''ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.”', 'Maya Angelou', 'Wisdom'),
  ('“A friend is someone who knows all about you and still loves you.”', 'Elbert Hubbard', 'Wisdom'),
  ('“To live is the rarest thing in the world. Most people exist, that is all.”', 'Oscar Wilde', 'Wisdom'),
  ('“Always forgive your enemies; nothing annoys them so much.”', 'Oscar Wilde', 'Wisdom'),
  ('“Live as if you were to die tomorrow. Learn as if you were to live forever.”', 'Mahatma Gandhi', 'Wisdom'),
  ('“I am so clever that sometimes I don''t understand a single word of what I am saying.”', 'Oscar Wilde', 'Wisdom'),
  ('“To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.”', 'Ralph Waldo Emerson', 'Wisdom'),
  ('“Here''s to the crazy ones. The misfits. The rebels. The troublemakers. The round pegs in the square holes. The ones who see things differently. They''re not fond of rules. And they have no respect for the status quo. You can quote them, disagree with them, glorify or vilify them. About the only thing you can''t do is ignore them. Because they change things. They push the human race forward. And while some may see them as the crazy ones, we see genius. Because the people who are crazy enough to think they can change the world, are the ones who do.”', 'Steve Jobs', 'Wisdom'),
  ('“Insanity is doing the same thing, over and over again, but expecting different results.”', 'Narcotics Anonymous', 'Wisdom'),
  ('“I believe that everything happens for a reason. People change so that you can learn to let go, things go wrong so that you appreciate them when they''re right, you believe lies so you eventually learn to trust no one but yourself, and sometimes good things fall apart so better things can fall together.”', 'Marilyn Monroe', 'Wisdom'),
  ('“It is better to be hated for what you are than to be loved for what you are not.”', 'Andre Gide', 'Wisdom'),
  ('“It is our choices, Harry, that show what we truly are, far more than our abilities.”', 'J.K. Rowling', 'Wisdom'),
  ('“It does not do to dwell on dreams and forget to live.”', 'J.K. Rowling', 'Wisdom'),
  ('“Good friends, good books, and a sleepy conscience: this is the ideal life.”', 'Mark Twain', 'Wisdom'),
  ('“The fool doth think he is wise, but the wise man knows himself to be a fool.”', 'William Shakespeare', 'Wisdom'),
  ('“It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it.”', 'Maurice Switzer', 'Wisdom'),
  ('“Whenever you find yourself on the side of the majority, it is time to reform (or pause and reflect).”', 'Mark Twain', 'Wisdom'),
  ('“Life is what happens to us while we are making other plans.”', 'Allen Saunders', 'Wisdom'),
  ('“A woman is like a tea bag; you never know how strong it is until it''s in hot water.”', 'Eleanor Roosevelt', 'Wisdom'),
  ('“The man who does not read has no advantage over the man who cannot read.”', 'Mark Twain', 'Wisdom'),
  ('“I may not have gone where I intended to go, but I think I have ended up where I needed to be.”', 'douglas adams', 'Wisdom'),
  ('“If you don''t stand for something you will fall for anything.”', 'Gordon A. Eadie', 'Wisdom'),
  ('“I solemnly swear that I am up to no good.”', 'J.K. Rowling', 'Wisdom'),
  ('“I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.”', 'Dr. Seuss', 'Wisdom'),
  ('“A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one.”', 'George R.R. Martin', 'Wisdom'),
  ('“', 'Kent M. Keith', 'Wisdom'),
  ('“For every minute you are angry you lose sixty seconds of happiness.”', 'Ralph Waldo Emerson', 'Wisdom'),
  ('“If you judge people, you have no time to love them.”', 'Mother Teresa', 'Wisdom'),
  ('“I''m not upset that you lied to me, I''m upset that from now on I can''t believe you.”', 'Friedrich Nietzsche', 'Wisdom'),
  ('“If you can''t explain it to a six year old, you don''t understand it yourself.”', 'Albert Einstein', 'Wisdom'),
  ('“If you only read the books that everyone else is reading, you can only think what everyone else is thinking.”', 'Haruki Murakami', 'Wisdom'),
  ('“I have always imagined that Paradise will be a kind of library.”', 'Jorge Luis Borges', 'Wisdom'),
  ('“We don''t see things as they are, we see them as we are.”', 'Anaïs Nin', 'Wisdom'),
  ('“Sometimes the questions are complicated and the answers are simple.”', 'Dr. Seuss', 'Wisdom'),
  ('“Never trust anyone who has not brought a book with them.”', 'Lemony Snicket', 'Wisdom'),
  ('“We read to know we''re not alone.”', 'William Nicholson', 'Wisdom'),
  ('“Sometimes, you read a book and it fills you with this weird evangelical zeal, and you become convinced that the shattered world will never be put back together unless and until all living humans read the book.”', 'John Green', 'Wisdom'),
  ('“Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?”', 'J.K. Rowling', 'Wisdom'),
  ('“Today you are You, that is truer than true. There is no one alive who is Youer than You.”', 'Dr. Seuss', 'Wisdom'),
  ('“I''m not afraid of death; I just don''t want to be there when it happens.”', 'Woody Allen', 'Wisdom'),
  ('“If one cannot enjoy reading a book over and over again, there is no use in reading it at all.”', 'Oscar Wilde', 'Wisdom'),
  ('“It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all—in which case, you fail by default.”', 'J.K. Rowling', 'Wisdom'),
  ('“If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.”', 'Albert Einstein', 'Wisdom'),
  ('“Logic will get you from A to Z; imagination will get you everywhere.”', 'Albert Einstein', 'Wisdom'),
  ('“Have you fallen in love with the wrong person yet?''Jace said, "Unfortunately, Lady of the Haven, my one true love remains myself."..."At least," she said, "you don''t have to worry about rejection, Jace Wayland.""Not necessarily. I turn myself down occasionally, just to keep it interesting.”', 'Cassandra Clare', 'Wisdom'),
  ('“Sometimes people are beautiful.Not in looks.Not in what they say.Just in what they are.”', 'Markus Zusak', 'Wisdom'),
  ('“The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.”', 'Bob Marley', 'Wisdom'),
  ('“The more that you read, the more things you will know. The more that you learn, the more places you''ll go.”', 'Dr. Seuss', 'Wisdom'),
  ('“Folks are usually about as happy as they make their minds up to be.”', 'Abraham Lincoln', 'Wisdom'),
  ('“There is no friend as loyal as a book.”', 'Ernest Hemingway', 'Wisdom'),
  ('“One good thing about music, when it hits you, you feel no pain.”', 'Bob Marley', 'Wisdom'),
  ('“Not all of us can do great things. But we can do small things with great love.”', 'Mother Teresa', 'Wisdom'),
  ('“If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you.”', 'Joan Powers', 'Wisdom'),
  ('“Life is like riding a bicycle. To keep your balance, you must keep moving.”', 'Albert Einstein', 'Wisdom'),
  ('“What really knocks me out is a book that, when you''re all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn''t happen much, though.”', 'J.D. Salinger', 'Wisdom'),
  ('“It matters not what someone is born, but what they grow to be.”', 'J.K. Rowling', 'Wisdom'),
  ('“The difference between genius and stupidity is: genius has its limits.”', 'Alexandre Dumas-fils', 'Wisdom'),
  ('“It is what you read when you don''t have to that determines what you will be when you can''t help it.”', 'Oscar Wilde', 'Wisdom'),
  ('“Not all those who wander are lost.”', 'J.R.R. Tolkien', 'Wisdom'),
  ('“Do one thing every day that scares you.”', 'Eleanor Roosevelt', 'Wisdom'),
  ('“You don’t have a soul, Doctor. You are a soul. You have a body, temporarily.”', 'Walter M. Miller Jr.', 'Wisdom'),
  ('“I would venture to guess that Anon, who wrote so many poems without signing them, was often a woman.”', 'Virginia Woolf', 'Wisdom'),
  ('“Some infinities are bigger than other infinities.”', 'John Green', 'Wisdom'),
  ('“One must always be careful of books," said Tessa, "and what is inside them, for words have the power to change us.”', 'Cassandra Clare', 'Wisdom'),
  ('“Reality continues to ruin my life.”', 'Bill Watterson', 'Wisdom'),
  ('“Time you enjoy wasting is not wasted time.”', 'Marthe Troly-Curtin', 'Wisdom'),
  ('“I wish it need not have happened in my time," said Frodo."So do I," said Gandalf, "and so do all who live to see such times. But that is not for them to decide. All we have to decide is what to do with the time that is given us.”', 'J.R.R. Tolkien', 'Wisdom'),
  ('“If there''s a book that you want to read, but it hasn''t been written yet, then you must write it.”', 'Toni Morrison', 'Wisdom'),
  ('“Who are you to judge the life I live?I know I''m not perfect-and I don''t live to be-but before you start pointing fingers...make sure you hands are clean!”', 'Bob Marley', 'Wisdom'),
  ('“I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! -- When I have a house of my own, I shall be miserable if I have not an excellent library.”', 'Jane Austen', 'Wisdom'),
  ('“The only way out of the labyrinth of suffering is to forgive.”', 'John Green', 'Wisdom'),
  ('“Piglet sidled up to Pooh from behind. "Pooh!" he whispered."Yes, Piglet?""Nothing," said Piglet, taking Pooh''s paw. "I just wanted to be sure of you.”', 'A.A. Milne', 'Wisdom'),
  ('“Go to heaven for the climate and hell for the company.”', 'Benjamin Franklin Wade', 'Wisdom'),
  ('“The reason I talk to myself is because I’m the only one whose answers I accept.”', 'George Carlin', 'Wisdom'),
  ('“A wise girl kisses but doesn''t love, listens but doesn''t believe, and leaves before she is left.”', 'Marilyn Monroe', 'Wisdom'),
  ('“Dumbledore watched her fly away, and as her silvery glow faded he turned back to Snape, and his eyes were full of tears."After all this time?""Always," said Snape.”', 'J.K. Rowling', 'Wisdom'),
  ('“There is nothing to writing. All you do is sit down at a typewriter and bleed.”', 'Ernest Hemingway', 'Wisdom'),
  ('“The books that the world calls immoral are books that show the world its own shame.”', 'Oscar Wilde', 'Wisdom'),
  ('“You should date a girl who reads.Date a girl who reads. Date a girl who spends her money on books instead of clothes, who has problems with closet space because she has too many books. Date a girl who has a list of books she wants to read, who has had a library card since she was twelve.Find a girl who reads. You’ll know that she does because she will always have an unread book in her bag. She’s the one lovingly looking over the shelves in the bookstore, the one who quietly cries out when she has found the book she wants. You see that weird chick sniffing the pages of an old book in a secondhand book shop? That’s the reader. They can never resist smelling the pages, especially when they are yellow and worn.She’s the girl reading while waiting in that coffee shop down the street. If you take a peek at her mug, the non-dairy creamer is floating on top because she’s kind of engrossed already. Lost in a world of the author’s making. Sit down. She might give you a glare, as most girls who read do not like to be interrupted. Ask her if she likes the book.Buy her another cup of coffee.Let her know what you really think of Murakami. See if she got through the first chapter of Fellowship. Understand that if she says she understood James Joyce’s Ulysses she’s just saying that to sound intelligent. Ask her if she loves Alice or she would like to be Alice.It’s easy to date a girl who reads. Give her books for her birthday, for Christmas, for anniversaries. Give her the gift of words, in poetry and in song. Give her Neruda, Pound, Sexton, Cummings. Let her know that you understand that words are love. Understand that she knows the difference between books and reality but by god, she’s going to try to make her life a little like her favorite book. It will never be your fault if she does.She has to give it a shot somehow.Lie to her. If she understands syntax, she will understand your need to lie. Behind words are other things: motivation, value, nuance, dialogue. It will not be the end of the world.Fail her. Because a girl who reads knows that failure always leads up to the climax. Because girls who read understand that all things must come to end, but that you can always write a sequel. That you can begin again and again and still be the hero. That life is meant to have a villain or two.Why be frightened of everything that you are not? Girls who read understand that people, like characters, develop. Except in the Twilight series.If you find a girl who reads, keep her close. When you find her up at 2 AM clutching a book to her chest and weeping, make her a cup of tea and hold her. You may lose her for a couple of hours but she will always come back to you. She’ll talk as if the characters in the book are real, because for a while, they always are.You will propose on a hot air balloon. Or during a rock concert. Or very casually next time she’s sick. Over Skype.You will smile so hard you will wonder why your heart hasn’t burst and bled out all over your chest yet. You will write the story of your lives, have kids with strange names and even stranger tastes. She will introduce your children to the Cat in the Hat and Aslan, maybe in the same day. You will walk the winters of your old age together and she will recite Keats under her breath while you shake the snow off your boots.Date a girl who reads because you deserve it. You deserve a girl who can give you the most colorful life imaginable. If you can only give her monotony, and stale hours and half-baked proposals, then you’re better off alone. If you want the world and the worlds beyond it, date a girl who reads.Or better yet, date a girl who writes.”', 'Rosemarie Urquico', 'Wisdom'),
  ('“′Classic′ - a book which people praise and don''t read.”', 'Mark Twain', 'Wisdom'),
  ('“I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.”', 'Marilyn Monroe', 'Wisdom'),
  ('“You don’t forget the face of the person who was your last hope.”', 'Suzanne Collins', 'Wisdom'),
  ('“I can never read all the books I want; I can never be all the people I want and live all the lives I want. I can never train myself in all the skills I want. And why do I want? I want to live and feel all the shades, tones and variations of mental and physical experience possible in my life. And I am horribly limited.”', 'Sylvia Plath', 'Wisdom'),
  ('“Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense.”', 'Ralph Waldo Emerson', 'Wisdom'),
  ('“I have never let my schooling interfere with my education.”', 'Mark Twain', 'Wisdom'),
  ('“You never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it.”', 'Harper Lee', 'Wisdom'),
  ('“The marks humans leave are too often scars.”', 'John Green', 'Wisdom'),
  ('“Some day you will be old enough to start reading fairy tales again.”', 'C.S. Lewis', 'Wisdom'),
  ('“And in that moment, I swear we were infinite.”', 'Stephen Chbosky', 'Wisdom'),
  ('“Anyone who has never made a mistake has never tried anything new.”', 'Albert Einstein', 'Wisdom'),
  ('“You know you''re in love when you can''t fall asleep because reality is finally better than your dreams.”', 'Dr. Seuss', 'Love'),
  ('“Only once in your life, I truly believe, you find someone who can completely turn your world around. You tell them things that you’ve never shared with another soul and they absorb everything you say and actually want to hear more. You share hopes for the future, dreams that will never come true, goals that were never achieved and the many disappointments life has thrown at you. When something wonderful happens, you can’t wait to tell them about it, knowing they will share in your excitement. They are not embarrassed to cry with you when you are hurting or laugh with you when you make a fool of yourself. Never do they hurt your feelings or make you feel like you are not good enough, but rather they build you up and show you the things about yourself that make you special and even beautiful. There is never any pressure, jealousy or competition but only a quiet calmness when they are around. You can be yourself and not worry about what they will think of you because they love you for who you are. The things that seem insignificant to most people such as a note, song or walk become invaluable treasures kept safe in your heart to cherish forever. Memories of your childhood come back and are so clear and vivid it’s like being young again. Colours seem brighter and more brilliant. Laughter seems part of daily life where before it was infrequent or didn’t exist at all. A phone call or two during the day helps to get you through a long day’s work and always brings a smile to your face. In their presence, there’s no need for continuous conversation, but you find you’re quite content in just having them nearby. Things that never interested you before become fascinating because you know they are important to this person who is so special to you. You think of this person on every occasion and in everything you do. Simple things bring them to mind like a pale blue sky, gentle wind or even a storm cloud on the horizon. You open your heart knowing that there’s a chance it may be broken one day and in opening your heart, you experience a love and joy that you never dreamed possible. You find that being vulnerable is the only way to allow your heart to feel true pleasure that’s so real it scares you. You find strength in knowing you have a true friend and possibly a soul mate who will remain loyal to the end. Life seems completely different, exciting and worthwhile. Your only hope and security is in knowing that they are a part of your life.”', 'Bob Marley', 'Love'),
  ('“As he read, I fell in love the way you fall asleep: slowly, and then all at once.”', 'John Green', 'Love'),
  ('“It is not a lack of love, but a lack of friendship that makes unhappy marriages.”', 'Friedrich Nietzsche', 'Love'),
  ('“I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close.”', 'Pablo Neruda', 'Love'),
  ('“Love all, trust a few,Do wrong to none: be able for thine enemyRather in power than use; and keep thy friendUnder thy own life''s key: be check''d for silence,But never tax''d for speech.”', 'William Shakespeare', 'Love'),
  ('“Have you ever been in love? Horrible isn''t it? It makes you so vulnerable. It opens your chest and it opens up your heart and it means that someone can get inside you and mess you up.”', 'Neil Gaiman', 'Love'),
  ('“This life is what you make it. No matter what, you''re going to mess up sometimes, it''s a universal truth. But the good part is you get to decide how you''re going to mess it up. Girls will be your friends - they''ll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they''re your true best friends. Don''t let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they''ll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can''t give up because if you give up, you''ll never find your soulmate. You''ll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn''t mean you''re gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don''t, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life''s a beautiful thing and there''s so much to smile about.”', 'Marilyn Monroe', 'Love'),
  ('“There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.”', 'Sarah Dessen', 'Love'),
  ('“Love is that condition in which the happiness of another person is essential to your own.”', 'Robert A. Heinlein', 'Love'),
  ('“You may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She''s not perfect—you aren''t either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. She may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break—her heart. So don''t hurt her, don''t change her, don''t analyze and don''t expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she''s not there.”', 'Bob Marley', 'Love'),
  ('“You love me. Real or not real?"I tell him, "Real.”', 'Suzanne Collins', 'Love'),
  ('“I''m in love with you," he said quietly."Augustus," I said."I am," he said. He was staring at me, and I could see the corners of his eyes crinkling. "I''m in love with you, and I''m not in the business of denying myself the simple pleasure of saying true things. I''m in love with you, and I know that love is just a shout into the void, and that oblivion is inevitable, and that we''re all doomed and that there will come a day when all our labor has been returned to dust, and I know the sun will swallow the only earth we''ll ever have, and I am in love with you.”', 'John Green', 'Love'),
  ('“I am nothing special, of this I am sure. I am a common man with common thoughts and I''ve led a common life. There are no monuments dedicated to me and my name will soon be forgotten, but I''ve loved another with all my heart and soul, and to me, this has always been enough..”', 'Nicholas Sparks', 'Love'),
  ('“Love looks not with the eyes, but with the mind; And therefore is wing''d Cupid painted blind. Nor hath love''s mind of any judgment taste; Wings and no eyes figure unheedy haste: And therefore is love said to be a child, Because in choice he is so oft beguil''d.”', 'William Shakespeare', 'Love'),
  ('“Love is like the wind, you can''t see it but you can feel it.”', 'Nicholas Sparks', 'Love'),
  ('“There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature.”', 'Jane Austen', 'Love'),
  ('“People think a soul mate is your perfect fit, and that''s what everyone wants. But a true soul mate is a mirror, the person who shows you everything that is holding you back, the person who brings you to your own attention so you can change your life. A true soul mate is probably the most important person you''ll ever meet, because they tear down your walls and smack you awake. But to live with a soul mate forever? Nah. Too painful. Soul mates, they come into your life just to reveal another layer of yourself to you, and then leave. A soul mates purpose is to shake you up, tear apart your ego a little bit, show you your obstacles and addictions, break your heart open so new light can get in, make you so desperate and out of control that you have to transform your life, then introduce you to your spiritual master...”', 'Elizabeth Gilbert', 'Love'),
  ('“You don''t love someone because they''re perfect, you love them in spite of the fact that they''re not.”', 'Jodi Picoult', 'Love'),
  ('“Love never dies a natural death. It dies because we don''t know how to replenish its source. It dies of blindness and errors and betrayals. It dies of illness and wounds; it dies of weariness, of witherings, of tarnishings.”', 'Anais Nin', 'Love'),
  ('“If you can make a woman laugh, you can make her do anything.”', 'Marilyn Monroe', 'Love'),
  ('“We’re all a little weird. And life is a little weird. And when we find someone whose weirdness is compatible with ours, we join up with them and fall into mutually satisfying weirdness—and call it love—true love.”', 'Robert Fulghum', 'Love'),
  ('“If I had a flower for every time I thought of you...I could walk through my garden forever.”', 'Alfred Tennyson', 'Love'),
  ('“There is no pretending," Jace said with absolute clarity. "I love you, and I will love you until I die, and if there is life after that, I''ll love you then.”', 'Cassandra Clare', 'Love'),
  ('“The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space.”', 'Marilyn Monroe', 'Love'),
  ('“To love at all is to be vulnerable. Love anything and your heart will be wrung and possibly broken. If you want to make sure of keeping it intact you must give it to no one, not even an animal. Wrap it carefully round with hobbies and little luxuries; avoid all entanglements. Lock it up safe in the casket or coffin of your selfishness. But in that casket, safe, dark, motionless, airless, it will change. It will not be broken; it will become unbreakable, impenetrable, irredeemable. To love is to be vulnerable.”', 'C.S. Lewis', 'Love'),
  ('“When someone loves you, the way they talk about you is different. You feel safe and comfortable.”', 'Jess C. Scott', 'Love'),
  ('“He''s like a drug for you, Bella.”', 'Stephenie Meyer', 'Love'),
  ('“Do not pity the dead, Harry. Pity the living, and, above all those who live without love.”', 'J.K. Rowling', 'Love'),
  ('“I''ve been making a list of the things they don''t teach you at school. They don''t teach you how to love somebody. They don''t teach you how to be famous. They don''t teach you how to be rich or how to be poor. They don''t teach you how to walk away from someone you don''t love any longer. They don''t teach you how to know what''s going on in someone else''s mind. They don''t teach you what to say to someone who''s dying. They don''t teach you anything worth knowing.”', 'Neil Gaiman', 'Love'),
  ('“A lady''s imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.”', 'Jane Austen', 'Love'),
  ('“To die will be an awfully big adventure.”', 'J.M. Barrie', 'Love'),
  ('“So it''s not gonna be easy. It''s going to be really hard; we''re gonna have to work at this everyday, but I want to do that because I want you. I want all of you, forever, everyday. You and me... everyday.”', 'Nicholas Sparks', 'Love'),
  ('“I love you as certain dark things are to be loved, in secret, between the shadow and the soul.”', 'Pablo Neruda', 'Love'),
  ('“Tis better to have loved and lostThan never to have loved at all.”', 'Alfred Lord Tennyson', 'Love'),
  ('“Oh, I wouldn''t mind, Hazel Grace. It would be a privilege to have my heart broken by you.”', 'John Green', 'Love'),
  ('“When we love, we always strive to become better than we are. When we strive to become better than we are, everything around us becomes better too.”', 'Paulo Coelho', 'Love'),
  ('“I no longer believed in the idea of soul mates, or love at first sight. But I was beginning to believe that a very few times in your life, if you were lucky, you might meet someone who was exactly right for you. Not because he was perfect, or because you were, but because your combined flaws were arranged in a way that allowed two separate beings to hinge together.”', 'Lisa Kleypas', 'Love'),
  ('“One is loved because one is loved. No reason is needed for loving.”', 'Paulo Coelho', 'Love'),
  ('“In vain have I struggled. It will not do. My feelings will not be repressed. You must allow me to tell you how ardently I admire and love you.”', 'Jane Austen', 'Love'),
  ('“He''s more myself than I am. Whatever our souls are made of, his and mine are the same.”', 'Emily Brontë', 'Love'),
  ('“Perhaps all the dragons in our lives are princesses who are only waiting to see us act, just once, with beauty and courage. Perhaps everything that frightens us is, in its deepest essence, something helpless that wants our love.”', 'Rainer Maria Rilke', 'Love'),
  ('“We love the things we love for what they are.”', 'Robert Frost', 'Love'),
  ('“I would die for you. But I won''t live for you.”', 'Stephen Chbosky', 'Love'),
  ('“Never love anyone who treats you like you''re ordinary.”', 'Oscar Wilde', 'Love'),
  ('“You can love someone so much...But you can never love people as much as you can miss them.”', 'John Green', 'Love'),
  ('“So, I love you because the entire universe conspired to help me find you.”', 'Paulo Coelho', 'Love'),
  ('“Love is needing someone. Love is putting up with someone''s bad qualities because they somehow complete you.”', 'Sarah Dessen', 'Love'),
  ('“Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It is not rude, it is not self-seeking, it is not easily angered, it keeps no record of wrongs. Love does not delight in evil but rejoices with the truth. It always protects, always trusts, always hopes, always perseveres.”', 'Anonymous', 'Love'),
  ('“I carry your heart with me (I carry it in my heart)I am never without it (anywhereI go you go,my dear; and whatever is done by only me is your doing,my darling)I fear no fate (for you are my fate,my sweet)I want no world (for beautiful you are my world,my true)and it''s you are whatever a moon has always meant and whatever a sun will always sing is youhere is the deepest secret nobody knows(here is the root of the root and the bud of the bud and the sky of the sky of a tree called life; which growshigher than the soul can hope or mind can hide)and this is the wonder that''s keeping the stars apartI carry your heart (I carry it in my heart)”', 'E.E. Cummings', 'Love'),
  ('“Indifference and neglect often do much more damage than outright dislike.”', 'J.K. Rowling', 'Love'),
  ('“The only thing worse than a boy who hates you: a boy that loves you.”', 'Markus Zusak', 'Love'),
  ('“You are my best friend as well as my lover, and I do not know which side of you I enjoy the most. I treasure each side, just as I have treasured our life together.”', 'Nicholas Sparks', 'Love'),
  ('“You are, and always have been, my dream.”', 'Nicholas Sparks', 'Love'),
  ('“I would always rather be happy than dignified.”', 'Charlotte Brontë', 'Love'),
  ('“And now I’m looking at you,” he said, “and you’re asking me if I still want you, as if I could stop loving you. As if I would want to give up the thing that makes me stronger than anything else ever has. I never dared give much of myself to anyone before – bits of myself to the Lightwoods, to Isabelle and Alec, but it took years to do it – but, Clary, since the first time I saw you, I have belonged to you completely. I still do. If you want me.”', 'Cassandra Clare', 'Love'),
  ('“Be kind, for everyone you meet is fighting a harder battle.”', 'Plato', 'Love'),
  ('“You can''t force love, I realized. It''s there or it isn''t. If it''s not there, you''ve got to be able to admit it. If it is there, you''ve got to do whatever it takes to protect the ones you love.”', 'Richelle Mead', 'Love'),
  ('“Every heart sings a song, incomplete, until another heart whispers back. Those who wish to sing always find a song. At the touch of a lover, everyone becomes a poet.”', 'Plato', 'Love'),
  ('“I think you still love me, but we can’t escape the fact that I’m not enough for you. I knew this was going to happen. So I’m not blaming you for falling in love with another woman. I’m not angry, either. I should be, but I’m not. I just feel pain. A lot of pain. I thought I could imagine how much this would hurt, but I was wrong.”', 'Haruki Murakami', 'Love'),
  ('“Doubt thou the stars are fire;Doubt that the sun doth move;Doubt truth to be a liar;But never doubt I love.”', 'William Shakespeare', 'Love'),
  ('“Some women choose to follow men, and some women choose to follow their dreams. If you''re wondering which way to go, remember that your career will never wake up and tell you that it doesn''t love you anymore.”', 'Lady Gaga', 'Love'),
  ('“The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed.”', 'Carl Gustav Jung', 'Love'),
  ('“And now here is my secret, a very simple secret: It is only with the heart that one can see rightly; what is essential is invisible to the eye.”', 'Antoine de Saint-Exupéry', 'Love'),
  ('“Nobody has ever measured, not even poets, how much the heart can hold.”', 'Zelda Fitzgerald', 'Love'),
  ('“The best love is the kind that awakens the soul and makes us reach for more, that plants a fire in our hearts and brings peace to our minds. And that''s what you''ve given me. That''s what I''d hoped to give you forever”', 'Nicholas Sparks', 'Love'),
  ('“Once upon a time there was a boy who loved a girl, and her laughter was a question he wanted to spend his whole life answering.”', 'Nicole Krauss', 'Love'),
  ('“Out beyond ideas of wrongdoing and rightdoing there is a field.I''ll meet you there.When the soul lies down in that grassthe world is too full to talk about.”', 'Rumi', 'Love'),
  ('“We loved with a love that was more than love.”', 'Edgar Allen Poe', 'Love'),
  ('“Eleanor was right. She never looked nice. She looked like art, and art wasn''t supposed to look nice; it was supposed to make you feel something.”', 'Rainbow Rowell', 'Love'),
  ('“We fell in love, despite our differences, and once we did, something rare and beautiful was created. For me, love like that has only happened once, and that''s why every minute we spent together has been seared in my memory. I''ll never forget a single moment of it.”', 'Nicholas Sparks', 'Love'),
  ('“And so the lion fell in love with the lamb…" he murmured. I looked away, hiding my eyes as I thrilled to the word."What a stupid lamb," I sighed."What a sick, masochistic lion.”', 'Stephenie Meyer', 'Love'),
  ('“This is a good sign, having a broken heart. It means we have tried for something.”', 'Elizabeth Gilbert', 'Love'),
  ('“And I''m suppose to sit by while you date boys and fall in love with someone else, get married...?" His voice tightened. "And meanwhile, I''ll die a little bit more every day, watching.”', 'Cassandra Clare', 'Love'),
  ('“The more I know of the world, the more I am convinced that I shall never see a man whom I can really love. I require so much!”', 'Jane Austen', 'Love'),
  ('“I wanted so badly to lie down next to her on the couch, to wrap my arms around her and sleep. Not fuck, like in those movies. Not even have sex. Just sleep together in the most innocent sense of the phrase. But I lacked the courage and she had a boyfriend and I was gawky and she was gorgeous and I was hopelessly boring and she was endlessly fascinating. So I walked back to my room and collapsed on the bottom bunk, thinking that if people were rain, I was drizzle and she was hurricane.”', 'John Green', 'Love'),
  ('“I heard what you said. I’m not the silly romantic you think. I don’t want the heavens or the shooting stars. I don’t want gemstones or gold. I have those things already. I want…a steady hand. A kind soul. I want to fall asleep, and wake, knowing my heart is safe. I want to love, and be loved.”', 'Shana Abe', 'Love'),
  ('“You can talk with someone for years, everyday, and still, it won''t mean as much as what you can have when you sit in front of someone, not saying a word, yet you feel that person with your heart, you feel like you have known the person for forever.... connections are made with the heart, not the tongue.”', 'C. JoyBell C.', 'Love'),
  ('“A guy and a girl can be just friends, but at one point or another, they will fall for each other...Maybe temporarily, maybe at the wrong time, maybe too late, or maybe forever”', 'Dave Matthews Band', 'Love'),
  ('“We live and breathe words. .... It was books that made me feel that perhaps I was not completely alone. They could be honest with me, and I with them. Reading your words, what you wrote, how you were lonely sometimes and afraid, but always brave; the way you saw the world, its colors and textures and sounds, I felt--I felt the way you thought, hoped, felt, dreamt. I felt I was dreaming and thinking and feeling with you. I dreamed what you dreamed, wanted what you wanted--and then I realized that truly I just wanted you.”', 'Cassandra Clare', 'Love'),
  ('“I have decided to stick to love...Hate is too great a burden to bear.”', 'Martin Luther King Jr.', 'Love'),
  ('“They say a person needs just three things to be truly happy in this world: someone to love, something to do, and something to hope for.”', 'Tom Bodett', 'Love'),
  ('“What''s meant to be will always find a way”', 'Trisha Yearwood', 'Love'),
  ('“Hearts are made to be broken.”', 'Oscar Wilde', 'Love'),
  ('“It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.”', 'Jane Austen', 'Love'),
  ('“Two people in love, alone, isolated from the world, that''s beautiful.”', 'Milan Kundera', 'Love'),
  ('“This above all: to thine own self be true, And it must follow, as the night the day, Thou canst not then be false to any man.”', 'William Shakespeare', 'Love'),
  ('“I have a history of making decisions very quickly about men. I have always fallen in love fast and without measuring risks. I have a tendency not only to see the best in everyone, but to assume that everyone is emotionally capable of reaching his highest potential. I have fallen in love more times than I care to count with the highest potential of a man, rather than with the man himself, and I have hung on to the relationship for a long time (sometimes far too long) waiting for the man to ascend to his own greatness. Many times in romance I have been a victim of my own optimism.”', 'Elizabeth Gilbert', 'Love'),
  ('“If all else perished, and he remained, I should still continue to be; and if all else remained, and he were annihilated, the universe would turn to a mighty stranger.”', 'Emily Jane Brontë ', 'Love'),
  ('“For the two of us, home isn''t a place. It is a person. And we are finally home.”', 'Stephanie Perkins', 'Love'),
  ('“No relationship is perfect, ever. There are always some ways you have to bend, to compromise, to give something up in order to gain something greater...The love we have for each other is bigger than these small differences. And that''s the key. It''s like a big pie chart, and the love in a relationship has to be the biggest piece. Love can make up for a lot.”', 'Sarah Dessen', 'Love'),
  ('“The very essence of romance is uncertainty.”', 'Oscar Wilde', 'Love'),
  ('“Love is always patient and kind. It is never jealous. Love is never boastful or conceited. It is never rude or selfish. It does not take offense and is not resentful. Love takes no pleasure in other people’s sins, but delights in the truth. It is always ready to excuse, to trust, to hope, and to endure whatever comes.”', 'Anonymous', 'Love'),
  ('“Love is so short, forgetting is so long.”', 'Pablo Neruda', 'Love'),
  ('“Have you ever been in love? Horrible isn''t it? It makes you so vulnerable. It opens your chest and it opens up your heart and it means that someone can get inside you and mess you up. You build up all these defenses, you build up a whole suit of armor, so that nothing can hurt you, then one stupid person, no different from any other stupid person, wanders into your stupid life...You give them a piece of you. They didn''t ask for it. They did something dumb one day, like kiss you or smile at you, and then your life isn''t your own anymore. Love takes hostages. It gets inside you. It eats you out and leaves you crying in the darkness, so simple a phrase like ''maybe we should be just friends'' turns into a glass splinter working its way into your heart. It hurts. Not just in the imagination. Not just in the mind. It''s a soul-hurt, a real gets-inside-you-and-rips-you-apart pain. I hate love.”', 'Neil Gaiman', 'Love'),
  ('“There is always some madness in love. But there is also always some reason in madness.”', 'Friedrich Nietzsche', 'Love'),
  ('“They didn’t agree on much. In fact, they didn’t agree on anything. They fought all the time and challenged each other ever day. But despite their differences, they had one important thing in common. They were crazy about each other.”', 'Nicholas Sparks', 'Love'),
  ('“We are all different. Don’t judge, understand instead.”', 'Roy T. Bennett', 'Love'),
  ('“I think if I''ve learned anything about friendship, it''s to hang in, stay connected, fight for them, and let them fight for you. Don''t walk away, don''t be distracted, don''t be too busy or tired, don''t take them for granted. Friends are part of the glue that holds life and faith together. Powerful stuff.”', 'Jon Katz', 'Love'),
  ('“You could have had anything else in the world, and you asked for me."She smiled up at him. Filthy as he was, covered in blood and dirt, he was the most beautiful thing she''d ever seen."But I don''t want anything else in the world.”', 'Cassandra Clare', 'Love'),
  ('“So many books, so little time.”', 'Frank Zappa', 'Humor'),
  ('“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”', 'Jane Austen', 'Humor'),
  ('“Outside of a dog, a book is man''s best friend. Inside of a dog it''s too dark to read.”', 'Groucho Marx', 'Humor'),
  ('“A day without sunshine is like, you know, night.”', 'Steve Martin', 'Humor'),
  ('“Never put off till tomorrow what may be done day after tomorrow just as well.”', 'Mark Twain', 'Humor'),
  ('“I love deadlines. I love the whooshing noise they make as they go by.”', 'Douglas Adams', 'Humor'),
  ('“Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car.”', 'Garrison Keillor', 'Humor'),
  ('“Women and cats will do as they please, and men and dogs should relax and get used to the idea.”', 'Robert A. Heinlein', 'Humor'),
  ('“All you need is love. But a little chocolate now and then doesn''t hurt.”', 'Charles M. Schulz', 'Humor'),
  ('“Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.”', 'Jim Henson', 'Humor'),
  ('“Whenever I feel the need to exercise, I lie down until it goes away.”', 'Paul   Terry', 'Humor'),
  ('“The story so far:In the beginning the Universe was created.This has made a lot of people very angry and been widely regarded as a bad move.”', 'Douglas Adams', 'Humor'),
  ('“I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.”', 'Groucho Marx', 'Humor'),
  ('“Some people never go crazy. What truly horrible lives they must lead.”', 'Charles Bukowski', 'Humor'),
  ('“Saying ''I notice you''re a nerd'' is like saying, ''Hey, I notice that you''d rather be intelligent than be stupid, that you''d rather be thoughtful than be vapid, that you believe that there are things that matter more than the arrest record of Lindsay Lohan. Why is that?'' In fact, it seems to me that most contemporary insults are pretty lame. Even ''lame'' is kind of lame. Saying ''You''re lame'' is like saying ''You walk with a limp.'' Yeah, whatever, so does 50 Cent, and he''s done all right for himself.”', 'John Green', 'Humor'),
  ('“The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.”', 'Terry Pratchett', 'Humor'),
  ('“I am free of all prejudice. I hate everyone equally. ”', 'W.C. Fields', 'Humor'),
  ('“I love mankind ... it''s people I can''t stand!!”', 'Charles M. Schulz', 'Humor'),
  ('“Remember, we''re madly in love, so it''s all right to kiss me anytime you feel like it.”', 'Suzanne Collins', 'Humor'),
  ('“Be nice to nerds. You may end up working for them. We all could.”', 'Charles J. Sykes', 'Humor'),
  ('“Do you remember me telling you we are practicing non-verbal spells, Potter?""Yes," said Harry stiffly."Yes, sir.""There''s no need to call me "sir" Professor."The words had escaped him before he knew what he was saying.”', 'J.K. Rowling', 'Humor'),
  ('“Jesus!" Luke exclaimed."Actually, it''s just me," said Simon. "Although I''ve been told the resemblance is startling.”', 'Cassandra Clare', 'Humor'),
  ('“Be careful about reading health books. Some fine day you''ll die of a misprint.”', 'Markus Herz', 'Humor'),
  ('“Fate is like a strange, unpopular restaurant filled with odd little waiters who bring you things you never asked for and don''t always like.”', 'Lemony Snicket', 'Humor'),
  ('“Creativity is knowing how to hide your sources”', 'C.E.M. Joad', 'Humor'),
  ('“Give a man a fire and he''s warm for a day, but set fire to him and he''s warm for the rest of his life.”', 'Terry Pratchett', 'Humor'),
  ('“The statistics on sanity are that one out of every four people is suffering from a mental illness. Look at your 3 best friends. If they''re ok, then it''s you.”', 'Rita Mae Brown', 'Humor'),
  ('“I don''t want to be a man," said Jace. "I want to be an angst-ridden teenager who can''t confront his own inner demons and takes it out verbally on other people instead.""Well," said Luke, "you''re doing a fantastic job.”', 'Cassandra Clare', 'Humor'),
  ('“I refuse to answer that question on the grounds that I don''t know the answer”', 'Douglas Adams', 'Humor'),
  ('“Never memorize something that you can look up.”', 'Albert Einstein', 'Humor'),
  ('“Wit beyond measure is man’s greatest treasure.”', 'J.K. Rowling', 'Humor'),
  ('“Is it true that you shouted at Professor Umbridge?""Yes.""You called her a liar?""Yes.""You told her He Who Must Not Be Named is back?""Yes.""Have a biscuit, Potter.”', 'J.K. Rowling', 'Humor'),
  ('“Mr. Moony presents his compliments to Professor Snape, and begs him to keep his abnormally large nose out of other people''s business.Mr. Prongs agrees with Mr. Moony, and would like to add that Professor Snape is an ugly git.Mr. Padfoot would like to register his astonishment that an idiot like that ever became a professor.Mr. Wormtail bids Professor Snape good day, and advises him to wash his hair, the slimeball.”', 'J.K. Rowling', 'Humor'),
  ('“He can run faster than Severus Snape confronted with shampoo.”', 'J.K. Rowling', 'Humor'),
  ('“When you''re in jail, a good friend will be trying to bail you out. A best friend will be in the cell next to you saying, ''Damn, that was fun''.”', 'Groucho Marx', 'Humor'),
  ('“Some humans would do anything to see if it was possible to do it. If you put a large switch in some cave somewhere, with a sign on it saying ''End-of-the-World Switch. PLEASE DO NOT TOUCH'', the paint wouldn''t even have time to dry.”', 'Terry Pratchett', 'Humor'),
  ('“When you are courting a nice girl an hour seems like a second. When you sit on a red-hot cinder a second seems like an hour. That''s relativity.”', 'Albert Einstein', 'Humor'),
  ('“There''s a fine line between genius and insanity. I have erased this line.”', 'Oscar Levant', 'Humor'),
  ('“Women are meant to be loved, not to be understood.”', 'Oscar Wilde', 'Humor'),
  ('“Wicked people never have time for reading. It''s one of the reasons for their wickedness.”', 'Lemony Snicket', 'Humor'),
  ('“Substitute ''damn'' every time you''re inclined to write ''very;'' your editor will delete it and the writing will be just as it should be.”', 'Mark Twain', 'Humor'),
  ('“I don''t want to go to heaven. None of my friends are there.”', 'Oscar Wilde', 'Humor'),
  ('“Death''s got an Invisibility Cloak?" Harry interrupted again."So he can sneak up on people," said Ron. "Sometimes he gets bored of running at them, flapping his arms and shrieking...”', 'J.K. Rowling', 'Humor'),
  ('“Let us find the dam snack bar," Zoe said. "We should eat while we can."Grover cracked a smile. "The dam snack bar?"Zoe blinked. "Yes. What is funny?""Nothing," Grover said, trying to keep a straight face. "I could use some dam french fries."Even Thalia smiled at that. "And I need to use the dam restroom."...I started cracking up, and Thalia and Grover joined in, while Zoe just looked at me. "I do not understand.""I want to use the dam water fountain," Grover said."And..." Thalia tried to catch her breath. "I want to buy a dam t-shirt.”', 'Rick Riordan', 'Humor'),
  ('“You know the world is going crazy when the best rapper is a white guy, the best golfer is a black guy, the tallest guy in the NBA is Chinese, the Swiss hold the America''s Cup, France is accusing the U.S. of arrogance, Germany doesn''t want to go to war, and the three most powerful men in America are named "Bush", "Dick", and "Colin." Need I say more?”', 'Chris Rock', 'Humor'),
  ('“It means ''Shadowhunters: Looking Better in Black Than the Widows of our Enemies Since 1234''.”', 'Cassandra Clare', 'Humor'),
  ('“Well, don''t expect us to be too impressed. We just saw Finnick Odair in his underwear.”', 'Suzanne Collins', 'Humor'),
  ('“Reader, suppose you were an idiot. And suppose you were a member of Congress. But I repeat myself.”', 'Mark Twain', 'Humor'),
  ('“I do not want people to be very agreeable, as it saves me the trouble of liking them a great deal.”', 'Jane Austen', 'Humor'),
  ('“Going to church doesn’t make you a Christian any more than going to a garage makes you an automobile.”', 'Billy Sunday', 'Humor'),
  ('“The planet is fine. The people are fucked.”', 'George Carlin', 'Humor'),
  ('“Reading is one form of escape. Running for your life is another.”', 'Lemony Snicket', 'Humor'),
  ('“I might be in love with you." He smiles a little. "I''m waiting until I''m sure to tell you, though.”', 'Veronica Roth', 'Humor'),
  ('“Do you remember back at the hotel when you promised that if we lived, you’d get dressed up in a nurse’s outfit and give me a sponge bath?" asked Jace."It was Simon who promised you the sponge bath.""As soon as I’m back on my feet, handsome," said Simon."I knew we should have left you a rat.”', 'Cassandra Clare', 'Humor'),
  ('“Never go to bed mad. Stay up and fight.”', 'Phyllis Diller', 'Humor'),
  ('“I like work: it fascinates me. I can sit and look at it for hours.”', 'Jerome K. Jerome', 'Humor'),
  ('“There are two motives for reading a book; one, that you enjoy it; the other, that you can boast about it.”', 'Bertrand Russell', 'Humor'),
  ('“Sarcasm is the last refuge of the imaginatively bankrupt.”', 'Cassandra Clare', 'Humor'),
  ('“Malachi scowled. "I don''t remember the Clave inviting you into the Glass City, Magnus Bane.""They didn''t," Magnus said. "Your wards are down.""Really?" the Consul''s voice dripped sarcasm. "I hadn''t noticed."Magnus looked concerned. "That''s terrible. Someone should have told you." He glanced at Luke. "Tell him the wards are down.”', 'Cassandra Clare', 'Humor'),
  ('“When his life was ruined, his family killed, his farm destroyed, Job knelt down on the ground and yelled up to the heavens, "Why god? Why me?" and the thundering voice of God answered, There''s just something about you that pisses me off.”', 'Stephen King', 'Humor'),
  ('“There is a theory which states that if ever anyone discovers exactly what the Universe is for and why it is here, it will instantly disappear and be replaced by something even more bizarre and inexplicable. There is another theory which states that this has already happened.”', 'Douglas Adams', 'Humor'),
  ('“THE FIRST TEN LIES THEY TELL YOU IN HIGH SCHOOL 1. We are here to help you. 2. You will have time to get to your class before the bell rings. 3. The dress code will be enforced. 4. No smoking is allowed on school grounds. 5. Our football team will win the championship this year. 6. We expect more of you here. 7. Guidance counselors are always available to listen. 8. Your schedule was created with you in mind. 9. Your locker combination is private. 10. These will be the years you look back on fondly. TEN MORE LIES THEY TELL YOU IN HIGH SCHOOL 1. You will use algebra in your adult lives. 2. Driving to school is a privilege that can be taken away. 3. Students must stay on campus during lunch. 4. The new text books will arrive any day now. 5. Colleges care more about you than your SAT scores. 6. We are enforcing the dress code. 7. We will figure out how to turn off the heat soon. 8. Our bus drivers are highly trained professionals. 9. There is nothing wrong with summer school. 10. We want to hear what you have to say.”', 'Laurie Halse Anderson', 'Humor'),
  ('“I did not attend his funeral, but I sent a nice letter saying I approved of it.”', 'Mark Twain', 'Humor'),
  ('“Where is human nature so weak as in the bookstore?”', 'Henry Ward Beecherr', 'Humor'),
  ('“Well, I’m not kissing the mundane," said Jace. "I’d rather stay down here and rot.""Forever?" said Simon. "Forever’s an awfully long time."Jace raised his eyebrows. "I knew it," he said. "You want to kiss me, don’t you?”', 'Cassandra Clare', 'Humor'),
  ('“What the hell is that?" I laughed."It''s my fox hat.""Your fox hat?""Yeah, Pudge. My fox hat.""Why are you wearing your fox hat?" I asked."Because no one can catch the motherfucking fox.”', 'John Green', 'Humor'),
  ('“Accept who you are. Unless you''re a serial killer.”', 'Ellen DeGeneres', 'Humor'),
  ('“I generally avoid temptation unless I can''t resist it.”', 'Mae West', 'Humor'),
  ('“It''s not true that I had nothing on. I had the radio on.”', 'Marilyn Monroe', 'Humor'),
  ('“So please, oh please, we beg, we pray,Go throw your TV set away,And in its place you can installA lovely bookshelf on the wall.Then fill the shelves with lots of books.”', 'Roald Dahl', 'Humor'),
  ('“Happiness is a warm puppy.”', 'Charles M. Schulz', 'Humor'),
  ('“Fantasy is a necessary ingredient in living, it''s a way of looking at life through the wrong end of a telescope.”', 'Dr. Seuss', 'Humor'),
  ('“Stories of imagination tend to upset those without one.”', 'Terry Pratchett', 'Humor'),
  ('“Everyone should be able to do one card trick, tell two jokes, and recite three poems, in case they are ever trapped in an elevator.”', 'Lemony Snicket', 'Humor'),
  ('“I have great faith in fools - self-confidence my friends will call it.”', 'Edgar Allan Poe', 'Humor'),
  ('“I think God, in creating man, somewhat overestimated his ability.”', 'Oscar Wilde', 'Humor'),
  ('“They love their hair because they''re not smart enough to love something more interesting.”', 'John Green', 'Humor'),
  ('“That does it," said Jace. "I''m going to get you a dictionary for Christmas this year.""Why?" Isabelle said."So you can look up ''fun.'' I''m not sure you know what it means.”', 'Cassandra Clare', 'Humor'),
  ('“But who prays for Satan? Who, in eighteen centuries, has had the common humanity to pray for the one sinner that needed it most?”', 'Mark Twain', 'Humor'),
  ('“Deadlines just aren''t real to me until I''m staring one in the face.”', 'Rick Riordan', 'Humor'),
  ('“I never travel without my diary. One should always have something sensational to read in the train.”', 'Oscar Wilde', 'Humor'),
  ('“Percy wouldn''t notice a joke if it danced naked in front of him wearing one of Dobby''s hats.”', 'J.K. Rowling', 'Humor'),
  ('“My tastes are simple: I am easily satisfied with the best.”', 'Winston S. Churchill', 'Humor'),
  ('“The fact that we live at the bottom of a deep gravity well, on the surface of a gas covered planet going around a nuclear fireball 90 million miles away and think this to be normal is obviously some indication of how skewed our perspective tends to be.”', 'Douglas Adams', 'Humor'),
  ('“You haven''t got a letter on yours," George observed. "I suppose she thinks you don''t forget your name. But we''re not stupid-we know we''re called Gred and Forge.”', 'J.K. Rowling', 'Humor'),
  ('“Happiness is having a large, loving, caring, close-knit family in another city.”', 'George Burns', 'Humor'),
  ('“There is nothing in the world so irresistibly contagious as laughter and good humor.”', 'Charles Dickens', 'Humor'),
  ('“Don''t talk to me.""Why not?""Because I want to fix that in my memory for ever. Draco Malfoy, the amazing bouncing ferret...”', 'J.K. Rowling', 'Humor'),
  ('“Once you can accept the universe as matter expanding into nothing that is something, wearing stripes with plaid comes easy.”', 'Albert Einstein', 'Humor'),
  ('“When life gives you lemons, squirt someone in the eye.”', 'Cathy Guiswite', 'Humor'),
  ('“Begin at the beginning," the King said, very gravely, "and go on till you come to the end: then stop.”', 'Lewis Carroll', 'Humor'),
  ('“Why are they all staring?" demanded Albus as he and Rose craned around to look at the other students."Don’t let it worry you," said Ron. "It’s me. I’m extremely famous.”', 'J.K. Rowling', 'Humor'),
  ('“I suppose I''ll have to add the force of gravity to my list of enemies.”', 'Lemony Snicket', 'Humor'),
  ('“Mom says it''s because she has PMS.Do you even know what that means?"I''m not a little kid anymore. It means pissed-at- men syndrome”', 'Nicholas Sparks', 'Humor'),
  ('“The Guide says there is an art to flying", said Ford, "or rather a knack. The knack lies in learning how to throw yourself at the ground and miss.”', 'Douglas Adams', 'Humor'),
  ('“Investigation?" Isabelle laughed. "Now we''re detectives? Maybe we should all have code names.""Good idea," said Jace. "I shall be Baron Hotschaft Von Hugenstein.”', 'Cassandra Clare', 'Humor'),
  ('“If writers wrote as carelessly as some people talk, then adhasdh asdglaseuyt[bn[ pasdlgkhasdfasdf.”', 'Lemony Snicket', 'Humor'),
  ('“Right now I’m having amnesia and déjà vu at the same time. I think I’ve forgotten this before.”', 'Steven Wright', 'Humor'),
  ('“What would men be without women? Scarce, sir...mighty scarce.”', 'Mark Twain', 'Humor'),
  ('“Don''t Panic.”', 'Douglas Adams', 'Humor'),
  ('“The Seven Social Sins are: Wealth without work. Pleasure without conscience. Knowledge without character. Commerce without morality. Science without humanity. Worship without sacrifice. Politics without principle.From a sermon given by Frederick Lewis Donaldson in Westminster Abbey, London, on March 20, 1925.”', 'Frederick Lewis Donaldson', 'Success'),
  ('“There is only one thing that makes a dream impossible to achieve: the fear of failure.”', 'Paulo Coelho', 'Success'),
  ('“It''s all right to love someone who doesn''t love you back, as long as they''re worth you loving them. As long as they deserve it.”', 'Cassandra Clare', 'Success'),
  ('“Women who seek to be equal with men lack ambition.”', 'Timothy Leary', 'Success'),
  ('“Ah,” said a voice from the doorway, “having your annual ‘everyone thinks Will is a lunatic’ meeting, are you? “It’s biannual,” said Jem. “And no, this is not that meeting.”', 'Cassandra Clare', 'Success'),
  ('“Tess, Tess, Tessa. Was there ever a more beautiful sound than your name? To speak it aloud makes my heart ring like a bell. Strange to imagine that, isn’t it – a heart ringing – but when you touch me that is what it is like: as if my heart is ringing in my chest and the sound shivers down my veins and splinters my bones with joy.Why have I written these words in this book? Because of you. You taught me to love this book where I had scorned it. When I read it for the second time, with an open mind and heart, I felt the most complete despair and envy of Sydney Carton. Yes, Sydney, for even if he had no hope that the woman he loved would love him, at least he could tell her of his love. At least he could do something to prove his passion, even if that thing was to die.I would have chosen death for a chance to tell you the truth, Tessa, if I could have been assured that death would be my own. And that is why I envied Sydney, for he was free.And now at last I am free, and I can finally tell you, without fear of danger to you, all that I feel in my heart.You are not the last dream of my soul.You are the first dream, the only dream I ever was unable to stop myself from dreaming. You are the first dream of my soul, and from that dream I hope will come all other dreams, a lifetime’s worth.With hope at least,Will Herondale”', 'Cassandra Clare', 'Success'),
  ('“Sometimes, when I have to do something I don''t want to do, I pretend I''m a character from a book. It''s easier to know what they would do.”', 'Cassandra Clare', 'Success'),
  ('“Whatever you are physically...male or female, strong or weak, ill or healthy--all those things matter less than what your heart contains. If you have the soul of a warrior, you are a warrior. All those other things, they are the glass that contains the lamp, but you are the light inside.”', 'Cassandra Clare', 'Success'),
  ('“Well, she''s not responding to my advances," he observed more brightly than he felt, "so she must be dead." "Or she''s a woman of good taste and sense.”', 'Cassandra Clare', 'Success'),
  ('“Will rolled up his sleeves. "We''ll probably have to knock down the door--" "Or," said Jem, reaching out and giving the knob a twist, "not." The door swung open onto a rectangle of darkness. "Now, that''s simply laziness," said Will.”', 'Cassandra Clare', 'Success');

-- Quotes import complete
